// BIST 100 constituents — Yahoo Finance symbol format (ticker.IS)
export const BIST100: { symbol: string; name: string }[] = [
  { symbol: "THYAO.IS", name: "Türk Hava Yolları" },
  { symbol: "AKBNK.IS", name: "Akbank" },
  { symbol: "GARAN.IS", name: "Garanti BBVA" },
  { symbol: "EREGL.IS", name: "Ereğli Demir Çelik" },
  { symbol: "ISCTR.IS", name: "İş Bankası C" },
  { symbol: "SAHOL.IS", name: "Sabancı Holding" },
  { symbol: "KCHOL.IS", name: "Koç Holding" },
  { symbol: "SISE.IS", name: "Şişe Cam" },
  { symbol: "BIMAS.IS", name: "BİM Mağazalar" },
  { symbol: "YKBNK.IS", name: "Yapı Kredi Bankası" },
  { symbol: "TCELL.IS", name: "Turkcell" },
  { symbol: "TOASO.IS", name: "Tofaş Oto. Fab." },
  { symbol: "FROTO.IS", name: "Ford Otosan" },
  { symbol: "TUPRS.IS", name: "Tüpraş" },
  { symbol: "PETKM.IS", name: "Petkim" },
  { symbol: "ARCLK.IS", name: "Arçelik" },
  { symbol: "HALKB.IS", name: "Halkbank" },
  { symbol: "VAKBN.IS", name: "Vakıfbank" },
  { symbol: "ASELS.IS", name: "Aselsan" },
  { symbol: "PGSUS.IS", name: "Pegasus" },
  { symbol: "EKGYO.IS", name: "Emlak Konut GYO" },
  { symbol: "DOHOL.IS", name: "Doğan Holding" },
  { symbol: "TAVHL.IS", name: "TAV Havalimanları" },
  { symbol: "CCOLA.IS", name: "Coca-Cola İçecek" },
  { symbol: "VESTL.IS", name: "Vestel" },
  { symbol: "TKFEN.IS", name: "Tekfen Holding" },
  { symbol: "LOGO.IS", name: "Logo Yazılım" },
  { symbol: "MGROS.IS", name: "Migros Ticaret" },
  { symbol: "OTKAR.IS", name: "Otokar" },
  { symbol: "KRDMD.IS", name: "Kardemir D" },
  { symbol: "OYAKC.IS", name: "Oyak Çimento" },
  { symbol: "KLNMA.IS", name: "Türkiye Kalkınma Bankası" },
  { symbol: "ENJSA.IS", name: "Enerjisa Enerji" },
  { symbol: "ENKAI.IS", name: "Enka İnşaat" },
  { symbol: "ULKER.IS", name: "Ülker Bisküvi" },
  { symbol: "AEFES.IS", name: "Anadolu Efes" },
  { symbol: "KONYA.IS", name: "Konya Çimento" },
  { symbol: "TTKOM.IS", name: "Türk Telekom" },
  { symbol: "TTRAK.IS", name: "Türk Traktör" },
  { symbol: "HEKTS.IS", name: "Hektaş" },
  { symbol: "GUBRF.IS", name: "Gübre Fabrikaları" },
  { symbol: "ISDMR.IS", name: "İskenderun Demir Çelik" },
  { symbol: "ALARK.IS", name: "Alarko Holding" },
  { symbol: "MPARK.IS", name: "MLP Sağlık" },
  { symbol: "DOAS.IS", name: "Doğuş Otomotiv" },
  { symbol: "CIMSA.IS", name: "Çimsa" },
  { symbol: "AYGAZ.IS", name: "Aygaz" },
  { symbol: "ZOREN.IS", name: "Zorlu Enerji" },
  { symbol: "AKSEN.IS", name: "Aksa Enerji" },
  { symbol: "TSKB.IS", name: "TSKB" },
  { symbol: "NETAS.IS", name: "Netaş" },
  { symbol: "KONTR.IS", name: "Kontrolmatik" },
  { symbol: "BRSAN.IS", name: "Borusan Mannesmann" },
  { symbol: "CLEBI.IS", name: "Çelebi Hava Servisi" },
  { symbol: "TURSG.IS", name: "Türkiye Sigorta" },
  { symbol: "AKSGY.IS", name: "Akiş GYO" },
  { symbol: "PEKGY.IS", name: "Pegasus GYO" },
  { symbol: "HLGYO.IS", name: "Halk GYO" },
  { symbol: "ISGYO.IS", name: "İş GYO" },
  { symbol: "TRGYO.IS", name: "Torunlar GYO" },
  { symbol: "GLYHO.IS", name: "Global Yatırım Holding" },
  { symbol: "EGEEN.IS", name: "Ege Endüstri" },
  { symbol: "ASUZU.IS", name: "Anadolu Isuzu" },
  { symbol: "SARKY.IS", name: "Sarkuysan" },
  { symbol: "SOKM.IS", name: "Şok Marketler" },
  { symbol: "ATAGY.IS", name: "Ata GYO" },
  { symbol: "KARSN.IS", name: "Karsan Otomotiv" },
  { symbol: "EUPWR.IS", name: "Europower" },
  { symbol: "ADEL.IS", name: "Adel Kalemcilik" },
  { symbol: "SMRTG.IS", name: "Smart Güneş" },
  { symbol: "MAVI.IS", name: "Mavi Giyim" },
  { symbol: "AKSA.IS", name: "Aksa Akrilik" },
  { symbol: "POLHO.IS", name: "Polisan Holding" },
  { symbol: "GOLTS.IS", name: "Göltaş Çimento" },
  { symbol: "HURGZ.IS", name: "Hürriyet" },
  { symbol: "BRKVY.IS", name: "Berkay" },
  { symbol: "ODAS.IS", name: "Odaş Elektrik" },
  { symbol: "JANTS.IS", name: "Jantsa" },
  { symbol: "KATMR.IS", name: "Katmerciler" },
  { symbol: "QUAGR.IS", name: "Qua Granite" },
  { symbol: "GEREL.IS", name: "Gersan Elektrik" },
  { symbol: "BALAT.IS", name: "Balatacılar" },
  { symbol: "NUHCM.IS", name: "Nuh Çimento" },
  { symbol: "AKFGY.IS", name: "Akfen GYO" },
  { symbol: "YEOTK.IS", name: "Yeo Teknoloji" },
  { symbol: "ATATP.IS", name: "Ata Tekstil" },
  { symbol: "ISSEN.IS", name: "İş İnşaat" },
  { symbol: "BTCIM.IS", name: "Batıçim" },
  { symbol: "GLCVY.IS", name: "Galata Wind" },
  { symbol: "KARTN.IS", name: "Kartonsan" },
  { symbol: "PRKME.IS", name: "Park Elektrik" },
];
